name: Release Please GitHub Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Only run on release commit
        if: startsWith(github.event.head_commit.message, 'chore(main): release')
        uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
