on:
    push:
      branches:
        - main
      paths-ignore:
        - '**.md'
  
  jobs:
    release:
      if: startsWith(github.event.head_commit.message, 'chore(main): release')
      runs-on: ubuntu-latest
      steps:
        - uses: google-github-actions/release-please-action@v4
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
  